# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt install tmux 
      - name: Get latest plugin
        run: ./install
        continue-on-error: true
      - run: ls -al $HOME
      - run: ls -al $HOME/.tmux
      - run: sudo ls -al /root
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dotfile
          path: |
            $HOME/.tmux
            !$HOME/.tmux/**/.git
            /home/runner/work/dotfile/
            !/home/runner/work/dotfile/*/.git

