# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt install tmux 
      - name: Get latest plugin
        run: sudo ./install
      - name: test tar
        run: |
          sudo ls -al  $HOME
          
      - name: Package
        run: sudo tar cf /home/runner/work/dotfile.tar.gz  ${{ GITHUB_WORKSPACE }}/dotfile  $HOME/.tmux
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: dotfile.tar.gz
          path: /home/runner/work/dotfile.tar.gz
